import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/Footer/Footer";
import { getCompanyData } from "./functions/get-data";
import { getHostName } from "./helper/hostname";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ToastWrapper from "./components/Toast/ToastWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Sell Sajilo",
  description: "Generated by sellsajilo",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hostname = await getHostName();
  const company = await getCompanyData(hostname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} font-poppins antialiased`}
      >
        <Navbar {...company} />
        {children}
        <ToastWrapper />
        <Footer {...company} />
      </body>
    </html>
  );
}
